### ISSUE TITLE
提案: ファイルエンコーディングのUTF-8(BOM付き)への変更

### ISSUE THREAD

**Issue by syundo0730** [furo-org/LittleSLAM#1]
このプロジェクトでは一部のファイルのエンコーディングとしてCP932が使われています。
これによって、以下の問題が生じています。

* プロジェクトをWebブラウザや、エンコーディングの自動認識に対応していないエディタから閲覧したときに文字化けが生じることがある
* コンパイルオプションとしてcharsetを指定しなければならない処理系がある。また、`-finput-charset=cp932`, `-fexec-charset=cp932`を指定してもgccのバージョンによっては正しくエンコーディングを変換できない、macOSのclang, gccで正しくエンコーディングを変換できない、といったことがある。

macOSについてはこのプロジェクトではサポートしていないようですが、対応すれば、プログラムを動作させられる読者を増やすことができるはずです。また、私はエンコーディングの変更と多少の修正を加えて、macOS上での動作の確認をしているので、対応のためのPull Requestを出す準備はあります。

提案
======
`*.cpp, *.h, *.md, CMakeList.txt` のファイルエンコーディングを一律、UTF-8 (BOM付き) に変換する

なぜこのファイルか?
------
`*.cpp, *.h`の変換は、ビルドに係る文字コードの問題を解決するために行います。
`*.md, CMakeList.txt`の変換はブラウザ等で閲覧したときの文字化けの問題を解決するために行います。
従来これらのファイルはcp932とASCIIが混在していましたが、同じ拡張子のものは同じエンコーディングにするため、一律UTF-8(with BOM) とすることを提案します。

なぜUTF-8 (BOM付き)?
------
UTF-8は標準的なUnicode符号化方式なので採用する妥当性はあると思います。
BOMを付与するのは、WindowsのVisual Studioにおいて、バージョンによってはBOM無しのUTF-8を正しく解釈できないが、BOMを付与すれば正しくエンコーディングを認識できるためです。

動作確認状況
------

上記の変更適用後、以下のOSで問題なく動作することを確認しました。

| OS                       | コンパイラ                  |
|--------------------------|-----------------------------|
| Windows 10               | VisualStudio 2017 C++ Compiler   |
| Ubuntu 16.04             | gcc 5.4.0                   |
| MacOS High Sierra (参考) | clang-900.0.39.2, gcc 7.3.0 |

Pull Request
------
上記提案に対応するPullRequestを作成しました https://github.com/furo-org/LittleSLAM/pull/2

**Comment by tomonoM** [comment]
ご提案ありがとうございます。
エンコーディングは、私も気になっていた部分で、BOMつきUTF-8にするのは良い案と思います。
pull requestにつきましては、内容の確認をとって適切に対応いたします。
来週初めころになるかと思います。

**Comment by tomonoM** [comment]
pull requestで提供されたスクリプトで、各ファイルがUTF-8-BOMに変換されることを確認しました。
また、Windows7, Windows10, Ubuntu16.04でのビルドおよびプログラム実行を確認しました。
このことから、ご提案の方法でエンコーディングの問題は解決することを確認しました。

ただ、Ubuntu14.04においてcmakeでエラーが発生し、ビルドできないという問題が発生しました。
これは、Ubuntu14.04のcmakeのデフォルトのバージョンが2.8.12であり、このバージョンでは
UTF-8-BOMを扱えないことが原因でした。
これに対処するために、CMakeLists.txtから日本語を削除し、CMakeLists.txtはすべて
BOMなしUTF-8（ASCII）となるように修正しました。

この対処のため、syundo0730さんのpull requestではなく、上記の修正を施したうえで新たにpull requestを起こして、ソースを更新することにしました。
有益なご提案、ありがとうございました。

**Comment by tomonoM** [comment]
MacOSにつきましては、実行環境をもっていないため、いまのところ、公式サポートはできない
というのが実情です。今後LittleSLAMを更新した際にMacOSへの対応を保証できないため、
syundo0730さんのMacOS対応版をこのリポジトリに取り込むことは残念ながらできません。
別のリポジトリを立てて公開されるとMacユーザに有益と思います。
よろしくお願いいたします。

**Comment by syundo0730** [comment]
動作ご確認いただき、ありがとうございました。cmakeのバージョンによる問題は想定外でした。お手数おかけしました。

> この対処のため、syundo0730さんのpull requestではなく、上記の修正を施したうえで新たにpull requestを起こして、ソースを更新することにしました。

承知しました。私のpull requestは適宜closeしていただければと思います。

> MacOSにつきましては、実行環境をもっていないため、いまのところ、公式サポートはできない
というのが実情です。

事情はわかりました。fork先で公開するか、個人的に利用するのにとどめようと思います。

いずれにせよ、ファイルエンコーディングをUTF-8にしていただけるのは、色々扱いやすくなるので有り難いです。よろしくお願いいたします。

**Comment by syundo0730** [comment]
https://github.com/furo-org/LittleSLAM/pull/3 で対応していただけたので、closeします

**Comment by hotsuyuki** [comment]
@syundo0730 横から失礼致します。git cloneしたコードそのままでmacOSで試そうとしたところ、
`Segmentation fault: 11`
とエラーが出てしまいました。同じようなエラーを経験されたことはございますでしょうか？

![screen shot 2018-09-27 at 18 05 02](https://user-images.githubusercontent.com/26198619/46135365-f8774000-c27f-11e8-8962-1bce113d0963.png)

ちなみに開発環境は、

| ソフトウェア | バージョン | インストール方法 |
|:------------:|:----------:|:----------------:|
| macOS High Sierra | 10.13.6  | -                    |
| Boost            | 1.67.0        | brew install boost |
| Eigen3          | 3.3.5         | brew install eigen |
| gnuplot         | 5.2            | brew install gnuplot --with-aquaterm |
| CMake          | 3.11.1         | 既にインストール済みだった |
| p2o               | beta          | git clone --recursive https://github.com/furo-org/LittleSLAM.git |

コンパイラは、

![screen shot 2018-09-27 at 18 18 07](https://user-images.githubusercontent.com/26198619/46136181-f57d4f00-c281-11e8-9ec6-50e9c4a8f4f6.png)

です。

**Comment by syundo0730** [comment]
@Hotsuyuki 
そのようなエラーを解決した差分がこちらになります。https://github.com/syundo0730/LittleSLAM/commit/092434bcd974c68c2cd5002e6efdbe48c4256a8f fork先のmasterにmacOSで動くものが置いてあります。ご参考になさってください。https://github.com/syundo0730/LittleSLAM

**Comment by hotsuyuki** [comment]
@syundo0730 ありがとうございます！見てみます！
